---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "recipes.labels" . | nindent 4 }}
spec:
  selector:
      {{- include "recipes.selectorLabels" . | nindent 4 }}
  ports:
  - port: 80
    targetPort: http
    name: http
    protocol: TCP
  - port: 8080
    targetPort: gunicorn
    name: gunicorn
    protocol: TCP