---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "recipes.labels" . | nindent 4 }}
data:
  nginx-config: |-
    events {
      worker_connections 1024;
    }
    http {
      include mime.types;
      server {
        listen 80;
        server_name _;

        client_max_body_size 16M;

        # serve static files
        location /static/ {
          alias /static/;
        }
        # serve media files
        location /media/ {
          alias /media/;
        }
      }
    }
