{{- if eq .Values.recipes.secretKey.existingSecret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-key
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "recipes.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if ne .Values.recipes.secretKey.keyString "" }}
  secret-key: {{ .Values.recipes.secretKey.keyString }}
  {{- else }}
    {{- $generated_secret_key := randAlphaNum 32 }}
  secret-key: {{ $generated_secret_key }}
  {{- end }}
{{- end }}
