apiVersion: v1
entries:
  recipes:
  - apiVersion: v2
    appVersion: 1.4.8
    created: "2023-07-24T09:25:45.028283+02:00"
    dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.2.3
    description: Application for managing recipes, planning meals, building shopping
      lists and much much more!
    digest: 2ce0137517adc52a983f12393b9890a8d28f2d9960db21e3ed238fa7608990bd
    name: recipes
    type: application
    urls:
    - https://github.com/nliakm/recipes/recipes-0.1.0.tgz
    version: 0.1.0
generated: "2023-07-24T09:25:45.017433+02:00"
